builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
checksum:
  name_template: "checksums.txt"
changelog:
  use: github-native
  sort: asc
brews:
  - name: workflow-sandbox
    homepage: "https://github.com/merschformann/workflow-sandbox"
    description: "A sandbox for GitHub Actions workflows"
    repository:
      owner: merschformann
      name: workflow-sandbox-brew
      token: "{{ .Env.BREW_TOKEN }}"
    commit_author:
      name: merschbotmann
      email: bot.merschformann@gmail.com
